<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Printable Riders Report</title>
    <style>
        /* ✅ Fix Layout Base Design */
        body {
            font-family: 'Times New Roman', Times, serif;
            background-color: #ffffff;
            color: #1f2937;
            font-size: 12px;
            margin: 40px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #1f2937;
            padding-bottom: 10px;
        }

        .header h1 {
            font-size: 22px;
            margin-bottom: 5px;
        }

        .header p {
            font-size: 12px;
            color: #4b5563;
        }

        .filters {
            margin-bottom: 20px;
            background-color: #f3f4f6;
            border: 1px solid #d1d5db;
            padding: 10px 15px;
            border-radius: 8px;
        }

        .filters p {
            margin: 3px 0;
            font-size: 12px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th {
            background-color: #1e3a8a;
            color: white;
            text-align: left;
            padding: 8px;
            border: 1px solid #d1d5db;
            font-size: 12px;
        }

        td {
            border: 1px solid #d1d5db;
            padding: 8px;
            vertical-align: middle;
            font-size: 12px;
        }

        tr:nth-child(even) {
            background-color: #f9fafb;
        }

        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .font-bold { font-weight: bold; }

        .footer {
            text-align: center;
            font-size: 10px;
            color: #6b7280;
            margin-top: 30px;
        }

        @media print {
            body {
                margin: 10mm;
            }
            .no-print {
                display: none;
            }
            .filters {
                page-break-inside: avoid;
            }
        }

        .btn-print {
            background-color: #1e3a8a;
            color: white;
            border: none;
            padding: 8px 14px;
            border-radius: 6px;
            cursor: pointer;
            font-size: 13px;
            box-shadow: 0 1px 3px rgba(0,0,0,0.3);
        }

        .btn-print:hover {
            background-color: #3748c2;
        }

    </style>
</head>
<body>

    <!-- Print Button -->
    <div class="no-print" style="text-align:right; margin-bottom:15px;">
        <button class="btn-print" onclick="window.print()">🖨️ Print Report</button>
    </div>

    <!-- Header -->
    <div class="header">
        <h1>🏍️ Riders Report</h1>
        <p>Generated on {{ now()->format('F d, Y g:i A') }}</p>
    </div>

    <!-- Filters Summary -->
    <div class="filters">
        <p><strong>Clinic:</strong> {{ $selectedClinic ? $selectedClinic->clinic_name : 'All Clinics' }}</p>
        <p><strong>Generated By:</strong> {{ auth()->user()->name ?? 'System' }}</p>
    </div>

    <!-- Riders Table -->
    <table>
        <thead>
            <tr>
                <th class="text-center" width="5%">#</th>
                <th>Rider Name</th>
                <th>Email</th>
                <th>Contact Number</th>
                <th class="text-center">Deliveries Count</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($riders as $rider)
                <tr>
                    <td class="text-center">{{ $loop->iteration }}</td>
                    <td>{{ $rider->name }}</td>
                    <td>{{ $rider->email }}</td>
                    <td>{{ $rider->contact_number ?? '-' }}</td>
                    <td class="text-center font-bold">{{ $rider->deliveries_count }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="5" class="text-center text-gray-500 py-4">No riders found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <!-- Footer -->
    <div class="footer">
        <p>Clinic Management System — {{ now()->year }}</p>
    </div>

</body>
</html>
