<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Riders Report</title>
    <style>
        /* --- Base Styles (your Fix Layout Design) --- */
        body {
            font-family: 'Times New Roman', Times, serif;
            margin: 40px;
            background-color: #ffffff;
            color: #1f2937;
            font-size: 12px;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #1f2937;
            padding-bottom: 10px;
        }

        .header h1 {
            font-size: 20px;
            margin-bottom: 4px;
        }

        .header p {
            font-size: 12px;
            color: #4b5563;
        }

        .filters {
            margin-bottom: 15px;
            background-color: #f3f4f6;
            border: 1px solid #d1d5db;
            padding: 10px 15px;
            border-radius: 8px;
        }

        .filters p {
            margin: 3px 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th {
            background-color: #1e3a8a;
            color: white;
            padding: 8px;
            text-align: left;
            font-size: 12px;
            border: 1px solid #d1d5db;
        }

        td {
            padding: 8px;
            border: 1px solid #d1d5db;
            vertical-align: middle;
        }

        tr:nth-child(even) {
            background-color: #f9fafb;
        }

        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .font-bold { font-weight: bold; }

        .footer {
            text-align: center;
            margin-top: 30px;
            font-size: 10px;
            color: #6b7280;
        }

        @page {
            margin: 40px;
        }

        @media print {
            body {
                margin: 10mm;
            }
            .filters {
                page-break-inside: avoid;
            }
        }
    </style>
</head>
<body>

    <!-- Header -->
    <div class="header">
        <h1>🏍️ Riders Report</h1>
        <p>{{ now()->format('F d, Y g:i A') }}</p>
    </div>

    <!-- Filters Summary -->
    <div class="filters">
        <p><strong>Clinic:</strong> 
            {{ $selectedClinic ? $selectedClinic->clinic_name : 'All Clinics' }}
        </p>
        <p><strong>Generated By:</strong> {{ auth()->user()->name ?? 'System' }}</p>
    </div>

    <!-- Riders Table -->
    <table>
        <thead>
            <tr>
                <th class="text-center" width="5%">#</th>
                <th>Rider Name</th>
                <th>Email</th>
                <th>Contact Number</th>
                <th class="text-center">Deliveries Count</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($riders as $rider)
                <tr>
                    <td class="text-center">{{ $loop->iteration }}</td>
                    <td>{{ $rider->name }}</td>
                    <td>{{ $rider->email }}</td>
                    <td>{{ $rider->contact_number ?? '-' }}</td>
                    <td class="text-center font-bold">{{ $rider->deliveries_count }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="5" class="text-center text-gray-500 py-4">No riders found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <!-- Footer -->
    <div class="footer">
        <p>Generated by Clinic Management System — {{ now()->year }}</p>
    </div>

</body>
</html>
