<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" href="{{ asset('images/logo3.ico') }}" type="image/x-icon">
    <title>Case Orders Report</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-100 text-gray-800">

    <div class="max-w-5xl mx-auto my-10 bg-white shadow-xl rounded-xl p-10">

      
        <div class="flex items-center justify-between border-b pb-4 mb-6">
            <div class="flex items-center space-x-3">
                <img src="{{ public_path('images/logo.png') }}" alt="Logo" class="w-14 h-14">
                <div>
                    <h1 class="text-2xl font-extrabold text-gray-800">Case Orders Report</h1>
                    <p class="text-sm text-gray-500">Jeffrey Dental Laboratory Management System</p>
                </div>
            </div>

            <div class="text-right text-sm text-gray-600">
                <p><strong>Date Generated:</strong> {{ now()->format('F j, Y g:i A') }}</p>
            </div>
        </div>

        <div class="overflow-x-auto rounded-xl shadow-lg mt-4">
            <table class="min-w-full bg-white border border-gray-200">
                <thead>
                    <tr class="bg-blue-900 text-white text-sm uppercase tracking-wide">
                        <th class="px-4 py-3 text-left">#</th>
                        <th class="px-4 py-3 text-left">Clinic</th>
                        <th class="px-4 py-3 text-left">Dentist</th>
                        <th class="px-4 py-3 text-left">Patient</th>
                        <th class="px-4 py-3 text-left">Status</th>
                        <th class="px-4 py-3 text-left">Created Date</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-gray-200 text-sm">
                    @foreach ($caseOrders as $index => $order)
                        <tr class="hover:bg-blue-50 transition-colors">
                            <td class="px-4 py-2 font-medium text-gray-700">{{ $index + 1 }}</td>
                            <td class="px-4 py-2">{{ $order->clinic->clinic_name ?? 'N/A' }}</td>
                            <td class="px-4 py-2">{{ $order->dentist->dentist_name ?? 'N/A' }}</td>
                            <td class="px-4 py-2">{{ $order->patient->fullname ?? 'N/A' }}</td>
                            <td class="px-4 py-2">
                                <span class="px-2 py-1 rounded text-xs font-semibold
                                    @if(($order->status ?? $order->delivery->delivery_status ?? $order->appointment->work_status) == 'completed')
                                        bg-green-100 text-green-700
                                    @elseif(($order->status ?? '') == 'pending')
                                        bg-yellow-100 text-yellow-700
                                    @else
                                        bg-gray-100 text-gray-700
                                    @endif">
                                    {{ $order->status ?? 
                                       $order->delivery->delivery_status ?? 
                                       $order->appointment->work_status ?? 
                                       'N/A' }}
                                </span>
                            </td>
                            <td class="px-4 py-2">{{ $order->created_at->format('F j, Y g:i A') }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

   
        <div class="mt-8 border-t pt-4 text-center text-xs text-gray-500">
            <p>Generated by: Jeffrey Dental Laboratory Management System | {{ config('app.name') }}</p>
        </div>
    </div>

</body>
</html>
